### PR TITLE
Dependency version ranges are changed to use Maven-supported syntax

### PR DESCRIPTION
**Pull request by yuqu**
Details: https://github.com/bitsofinfo/hazelcast-docker-swarm-discovery-spi/issues/17

### CODE REVIEW

**Comment by yuqu** [comment]
I wasn't sure if hazelcast 3.10 and above are going to create any issue, and since you had explicitly set the hazelcast version 3.9.+ on the last update, I've set 3.10-BETA-1 as the upper boundary(excluded) to make sure that the build will have the latest 3.9.x version.

**Comment by yuqu** [comment]
I wasn't sure if hazelcast 3.10 and above are going to create any issue, and since you had explicitly set the hazelcast version 3.9.+ on the last update, I've set 3.10-BETA-1 as the upper boundary(excluded) to make sure that the build will have the latest 3.9.x version.

**Comment by bitsofinfo** [comment]
k lets see what build does

**Comment by bitsofinfo** [comment]
built, tagged published. Thanks! Please star the project if you find it useful

**Pull request merged**
