### PR TITLE
Add Docker Swarm DNSRR Discovery Strategy

### PR DESCRIPTION
**Pull request by Cardds**
Adds discovery strategy that relies on endpoint mode being set to
dnsrr in docker, but eliminates the need for addresses of the
swarm manager (and any need for exposing the docker HTTP API port).

### CODE REVIEW

**Comment by bitsofinfo** [comment]
Looks interesting, thank you! 

Please provide a good documentation section in the README as well to go along with this and how it can be configured in lieu of the existing behaviors of the SPI. The documentation will need a good update.

**Comment by bitsofinfo** [comment]
Also please update the `.travis.yml` config to incorporate appropriate tests for this new config option

**Comment by Cardds** [comment]
Added basic test cases in separate commit. More intensive/expansive tests may be added in a separate PR at a later date. Note that timeout/file length was increased for this section due to inconsistency in reaction times to cluster state change.

README & docs to be added in the next commit.

**Comment by Cardds** [comment]
The README has been updated with comments on the XML configuration.

**Comment by bitsofinfo** [comment]
Thanks! please take a look at: https://travis-ci.org/bitsofinfo/hazelcast-docker-swarm-discovery-spi/builds/332887211

**Comment by bitsofinfo** [comment]
Released and published to bintray/maven, thanks man!

**Pull request merged**
