### PR TITLE
Diamond operator and private constructors

### PR DESCRIPTION
**Pull request by robinroos**
Four non-functional refactorings:
* The diamond operator("<>") should be used
* Utility classes should not have public constructors
* Collection.isEmpty() should be used to test for emptiness
* Synchronized classes Vector, Hashtable, Stack and StringBuffer should not be used

### CODE REVIEW

**Comment by robinroos** [comment]
I have further refactorings to push as soon as these ones are merged.  I don't want to keep adding more and more commits as it would make it hard for you to see and to review precisely what is being changed.

**Comment by robinroos** [comment]
I have commits for the next three refactoring PRs lines up. I don’t want to add commits to this one (as stated),  or do I want to create new PRs before this is merged (to avoid merge conflicts). 

Would you perhaps be able to merge this one tonight?

**Comment by bitsofinfo** [comment]
FYI the functional change addressing your issue has been available in RC14 after the previous PR was merged. What function these new PRs addressing? You said there are additional ones beyond this one which appears to be just some minor coding changes.

**Comment by robinroos** [comment]
Yes, we just went live using RC14.  

I’m tidying up code and coding style with these PRs, not addressing any known functional issues. so that everything will be a bit cleaner before you publish 1.0.

**Comment by bitsofinfo** [comment]
thats fine, please just make sure all changes are java 7 compat should anyone else be using that as a baseline to work in this code (or update README) Really should be whatever min Java Hazelcast 3.9+ is baselined for

**Pull request merged**
